# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: leela
# "service" is the name of this project. This will also be added to your AWS resource names.
service: orderService

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    REGION: ap-south-1
    DYNAMODB_TABLE: Orders
    SQS_ORDER_QUEUE_URL: https://sqs.ap-south-1.amazonaws.com/117915829123/OrderQueue
  # httpApi:
  #   authorizers:
  #     myCognitoAuth:
  #       identitySource: $request.header.Authorization   #Extract JWT Token from Authorization Header
  #       # who issued the token - URL of cognito pool (Need to verify tokens)
  #       issuerUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_yFvZMbwFb
  #       # cognito App clientID
  #       audience:
  #         - ${ssm:/CLIENT_ID}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: !GetAtt OrdersTable.Arn
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource: !GetAtt OrderQueue.Arn
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource: arn:aws:states:ap-south-1:117915829123:stateMachine:OrderProcessingStateMachine
resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue

functions:
  placeOrder:
    handler: handlers/placeOrder.placeOrder
    environment:
      STEP_FUNCTION_ARN: 
        Ref: OrderProcessingStateMachine
    events:
      - httpApi:
          path: /create-order
          method: post
          # authorizer:
          #   name: myCognitoAuth
  processOrder:
    handler: handlers/processOrder.processOrder
    events:
      - sqs:
          arn: !GetAtt OrderQueue.Arn
  updateOrderStatus:
    handler: handlers/updateOrderStatus.updateOrderStatus

stepFunctions:
  stateMachines:
    OrderProcessingStateMachine:
      name: OrderProcessingStateMachine
      definition:
        Comment: "Order Processing with status update"
        StartAt: UpdateStatusToProcessing
        States:
          UpdateStatusToProcessing:
            Type: Task
            Resource: !GetAtt updateOrderStatus.Arn
            Next: NotifyUser
          NotifyUser:
            Type: Pass
            Result: "User Notified"
            End: true

