# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: leela
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    REGION: ap-south-1
    BUCKET_NAME: category-images-leela239
    DYNAMODB_TABLE: Categories
    SNS_CATEGORY_CLEANUP_TOPIC_ARN: arn:aws:sns:ap-south-1:117915829123:CategoryCleanupTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::category-images-leela239/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:ap-south-1:117915829123:table/Categories
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:ap-south-1:117915829123:CategoryCleanupTopic

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-leela239

    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH

    CategoryCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CategoryCleanupTopic
    CategoryCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref CategoryCleanupTopic
        Protocol: email
        Endpoint: leelajobs239@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /uplaod-url
          method: post
  updateCategoryImage:
    handler: handlers/updateCategoryImage.updateCategoryImage
    events:
      - s3:
          bucket: category-images-leela239
          event: s3:ObjectCreated:Put
          existing: true
  cleanupCategories:
    handler: handlers/cleanupCategories.cleanupCategories
    events:
      - schedule: rate(2 minutes)
