# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: leela
# "service" is the name of this project. This will also be added to your AWS resource names.
service: authService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  environment:
    CLIENT_ID: ${ssm:/CLIENT_ID}
    CLIENT_SECRET: ${ssm:/CLIENT_SECRET}
    REGION: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

functions:
  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /signUp
          method: post
  confirmSignup:
    handler: handlers/confirmSignup.confirmSignup
    events:
      - httpApi:
          path: /confirmSignup
          method: post
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /signIn
          method: post
  signOut:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /signOut
          method: post
  forgotPassword:
    handler: handlers/forgotPassword.forgotPassword
    events:
      - httpApi:
          path: /forgot-password
          method: post
  confirmForgotPassword:
    handler: handlers/confirmForgotPassword.confirmForgotPassword
    events:
      - httpApi:
          path: /confirm-forgot-password
          method: post